version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: sagarsdocker/springboordocker:springbootapp
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "4005:8080"
    networks:
      - webnet
networks:
  webnet:
